# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: nageshr 
# spec:
#   profile:
#     displayName: user_nagesh 
#     email: nagesh@redhat.com
#   memberOf: [User, Group]
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: fname
spec:
  profile:
    displayName: Fname Lname
    picture: https://blah.com/fname
  memberOf:
    - engineering
