schemaVersion: 2.1.0
metadata:
  generateName: ${{values.repoName}}
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: development-tooling
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.4
      # env:
      #   - name: QUARKUS_HTTP_HOST
      #     value: 0.0.0.0
      #   - name: MAVEN_OPTS
      #     value: "-Dmaven.repo.local=/home/user/.m2/repository" 
      memoryLimit: 5Gi
      cpuLimit: 2500m
      volumeMounts:
        - name: npm
          path: /home/user/.npm
      endpoints:
        - name: react-development-server
          targetPort: 3000
          exposure: public
          secure: false
          protocol: http
        - name: debug
          targetPort: 3000
          exposure: none
          secure: false
          protocol: tcp
        - name: tests
          targetPort: 3000
          exposure: none
          secure: false
          protocol: tcp          
  - name: npm
    volume:
      size: 1G
commands:
  - id: package
    exec:
      label: "1. Package the application"
      component: development-tooling
      commandLine: "npm build"
      group:
        kind: build
        isDefault: true
  - id: start-dev
    exec:
      label: "2. Start Development mode (Hot reload + debug)"
      component: development-tooling
      commandLine: "npm start"
      group:
        kind: run
        isDefault: true
  # - id: fix-java-version
  #   exec:
  #     component: development-tooling
  #     commandLine: 'rm -rf ${HOME}/.java/current/* && ln -s /usr/lib/jvm/java-17-openjdk/* ${HOME}/.java/current'
# events:
#   postStart:
#     - fix-java-version
